'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type SelectionValue, type UiToggleGroupCustomEvent } from "@components/core";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@components/core/dist/components/my-component.js";
import { UiChipGroup as UiChipGroupElement, defineCustomElement as defineUiChipGroup } from "@components/core/dist/components/ui-chip-group.js";
import { UiChip as UiChipElement, defineCustomElement as defineUiChip } from "@components/core/dist/components/ui-chip.js";
import { UiInputGroupAddon as UiInputGroupAddonElement, defineCustomElement as defineUiInputGroupAddon } from "@components/core/dist/components/ui-input-group-addon.js";
import { UiInputGroupInput as UiInputGroupInputElement, defineCustomElement as defineUiInputGroupInput } from "@components/core/dist/components/ui-input-group-input.js";
import { UiInputGroup as UiInputGroupElement, defineCustomElement as defineUiInputGroup } from "@components/core/dist/components/ui-input-group.js";
import { UiRadioGroup as UiRadioGroupElement, defineCustomElement as defineUiRadioGroup } from "@components/core/dist/components/ui-radio-group.js";
import { UiRadio as UiRadioElement, defineCustomElement as defineUiRadio } from "@components/core/dist/components/ui-radio.js";
import { UiTabList as UiTabListElement, defineCustomElement as defineUiTabList } from "@components/core/dist/components/ui-tab-list.js";
import { UiTabPanel as UiTabPanelElement, defineCustomElement as defineUiTabPanel } from "@components/core/dist/components/ui-tab-panel.js";
import { UiTab as UiTabElement, defineCustomElement as defineUiTab } from "@components/core/dist/components/ui-tab.js";
import { UiTabs as UiTabsElement, defineCustomElement as defineUiTabs } from "@components/core/dist/components/ui-tabs.js";
import { UiToggleGroup as UiToggleGroupElement, defineCustomElement as defineUiToggleGroup } from "@components/core/dist/components/ui-toggle-group.js";
import { UiToggle as UiToggleElement, defineCustomElement as defineUiToggle } from "@components/core/dist/components/ui-toggle.js";
import { UiTooltip as UiTooltipElement, defineCustomElement as defineUiTooltip } from "@components/core/dist/components/ui-tooltip.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

export type UiChipEvents = { onRemove: EventName<CustomEvent<string>> };

export const UiChip: StencilReactComponent<UiChipElement, UiChipEvents> = /*@__PURE__*/ createComponent<UiChipElement, UiChipEvents>({
    tagName: 'ui-chip',
    elementClass: UiChipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onRemove: 'remove' } as UiChipEvents,
    defineCustomElement: defineUiChip
});

export type UiChipGroupEvents = {
    onValueChange: EventName<CustomEvent<string[]>>,
    onChipRemove: EventName<CustomEvent<string>>
};

export const UiChipGroup: StencilReactComponent<UiChipGroupElement, UiChipGroupEvents> = /*@__PURE__*/ createComponent<UiChipGroupElement, UiChipGroupEvents>({
    tagName: 'ui-chip-group',
    elementClass: UiChipGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onChipRemove: 'chipRemove'
    } as UiChipGroupEvents,
    defineCustomElement: defineUiChipGroup
});

export type UiInputGroupEvents = NonNullable<unknown>;

export const UiInputGroup: StencilReactComponent<UiInputGroupElement, UiInputGroupEvents> = /*@__PURE__*/ createComponent<UiInputGroupElement, UiInputGroupEvents>({
    tagName: 'ui-input-group',
    elementClass: UiInputGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiInputGroupEvents,
    defineCustomElement: defineUiInputGroup
});

export type UiInputGroupAddonEvents = NonNullable<unknown>;

export const UiInputGroupAddon: StencilReactComponent<UiInputGroupAddonElement, UiInputGroupAddonEvents> = /*@__PURE__*/ createComponent<UiInputGroupAddonElement, UiInputGroupAddonEvents>({
    tagName: 'ui-input-group-addon',
    elementClass: UiInputGroupAddonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiInputGroupAddonEvents,
    defineCustomElement: defineUiInputGroupAddon
});

export type UiInputGroupInputEvents = {
    onInputChange: EventName<CustomEvent<string>>,
    onInputInput: EventName<CustomEvent<string>>,
    onInputFocus: EventName<CustomEvent<void>>,
    onInputBlur: EventName<CustomEvent<void>>
};

export const UiInputGroupInput: StencilReactComponent<UiInputGroupInputElement, UiInputGroupInputEvents> = /*@__PURE__*/ createComponent<UiInputGroupInputElement, UiInputGroupInputEvents>({
    tagName: 'ui-input-group-input',
    elementClass: UiInputGroupInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onInputChange: 'inputChange',
        onInputInput: 'inputInput',
        onInputFocus: 'inputFocus',
        onInputBlur: 'inputBlur'
    } as UiInputGroupInputEvents,
    defineCustomElement: defineUiInputGroupInput
});

export type UiRadioEvents = NonNullable<unknown>;

export const UiRadio: StencilReactComponent<UiRadioElement, UiRadioEvents> = /*@__PURE__*/ createComponent<UiRadioElement, UiRadioEvents>({
    tagName: 'ui-radio',
    elementClass: UiRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiRadioEvents,
    defineCustomElement: defineUiRadio
});

export type UiRadioGroupEvents = { onValueChange: EventName<CustomEvent<string>> };

export const UiRadioGroup: StencilReactComponent<UiRadioGroupElement, UiRadioGroupEvents> = /*@__PURE__*/ createComponent<UiRadioGroupElement, UiRadioGroupEvents>({
    tagName: 'ui-radio-group',
    elementClass: UiRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as UiRadioGroupEvents,
    defineCustomElement: defineUiRadioGroup
});

export type UiTabEvents = NonNullable<unknown>;

export const UiTab: StencilReactComponent<UiTabElement, UiTabEvents> = /*@__PURE__*/ createComponent<UiTabElement, UiTabEvents>({
    tagName: 'ui-tab',
    elementClass: UiTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiTabEvents,
    defineCustomElement: defineUiTab
});

export type UiTabListEvents = NonNullable<unknown>;

export const UiTabList: StencilReactComponent<UiTabListElement, UiTabListEvents> = /*@__PURE__*/ createComponent<UiTabListElement, UiTabListEvents>({
    tagName: 'ui-tab-list',
    elementClass: UiTabListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiTabListEvents,
    defineCustomElement: defineUiTabList
});

export type UiTabPanelEvents = NonNullable<unknown>;

export const UiTabPanel: StencilReactComponent<UiTabPanelElement, UiTabPanelEvents> = /*@__PURE__*/ createComponent<UiTabPanelElement, UiTabPanelEvents>({
    tagName: 'ui-tab-panel',
    elementClass: UiTabPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiTabPanelEvents,
    defineCustomElement: defineUiTabPanel
});

export type UiTabsEvents = { onValueChange: EventName<CustomEvent<string>> };

export const UiTabs: StencilReactComponent<UiTabsElement, UiTabsEvents> = /*@__PURE__*/ createComponent<UiTabsElement, UiTabsEvents>({
    tagName: 'ui-tabs',
    elementClass: UiTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as UiTabsEvents,
    defineCustomElement: defineUiTabs
});

export type UiToggleEvents = NonNullable<unknown>;

export const UiToggle: StencilReactComponent<UiToggleElement, UiToggleEvents> = /*@__PURE__*/ createComponent<UiToggleElement, UiToggleEvents>({
    tagName: 'ui-toggle',
    elementClass: UiToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiToggleEvents,
    defineCustomElement: defineUiToggle
});

export type UiToggleGroupEvents = { onValueChange: EventName<UiToggleGroupCustomEvent<SelectionValue>> };

export const UiToggleGroup: StencilReactComponent<UiToggleGroupElement, UiToggleGroupEvents> = /*@__PURE__*/ createComponent<UiToggleGroupElement, UiToggleGroupEvents>({
    tagName: 'ui-toggle-group',
    elementClass: UiToggleGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as UiToggleGroupEvents,
    defineCustomElement: defineUiToggleGroup
});

export type UiTooltipEvents = NonNullable<unknown>;

export const UiTooltip: StencilReactComponent<UiTooltipElement, UiTooltipEvents> = /*@__PURE__*/ createComponent<UiTooltipElement, UiTooltipEvents>({
    tagName: 'ui-tooltip',
    elementClass: UiTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as UiTooltipEvents,
    defineCustomElement: defineUiTooltip
});
