/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FieldMessage } from "./components/uefds-field/uefds-field";
export { FieldMessage } from "./components/uefds-field/uefds-field";
export namespace Components {
    interface UefdsAddon {
        /**
          * @default 'start'
         */
        "align": 'start' | 'end';
        /**
          * @default false
         */
        "clickable": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'muted' | 'transparent';
    }
    interface UefdsButton {
        /**
          * @default false
         */
        "busy": boolean;
        /**
          * @default 'theme'
         */
        "color": 'theme' | 'success' | 'warning' | 'danger' | 'info';
        /**
          * @default 'horizontal'
         */
        "direction": 'vertical' | 'horizontal';
        /**
          * @default false
         */
        "disabled": boolean;
        "iconEnd": string;
        "iconStart": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        "text": string;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset' | 'clear';
        /**
          * @default 'solid'
         */
        "variant": 'outline' | 'solid' | 'subtle' | 'link';
    }
    interface UefdsField {
        "instructions": string;
        "label": string;
        /**
          * @default []
         */
        "messages": FieldMessage[];
        /**
          * @default false
         */
        "required": boolean;
        "support": string;
    }
    interface UefdsFieldset {
    }
    interface UefdsForm {
    }
    interface UefdsIcon {
        "name": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg' | 'xl';
    }
    interface UefdsInputGroup {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "error": boolean;
        /**
          * @default 'base'
         */
        "size": 'sm' | 'base' | 'lg';
    }
    interface UefdsTextbox {
        /**
          * @default false
         */
        "disabled": boolean;
        "maxlength": number;
        "name": string;
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface UefdsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUefdsButtonElement;
}
export interface UefdsTextboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUefdsTextboxElement;
}
declare global {
    interface HTMLUefdsAddonElement extends Components.UefdsAddon, HTMLStencilElement {
    }
    var HTMLUefdsAddonElement: {
        prototype: HTMLUefdsAddonElement;
        new (): HTMLUefdsAddonElement;
    };
    interface HTMLUefdsButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLUefdsButtonElement extends Components.UefdsButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUefdsButtonElementEventMap>(type: K, listener: (this: HTMLUefdsButtonElement, ev: UefdsButtonCustomEvent<HTMLUefdsButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUefdsButtonElementEventMap>(type: K, listener: (this: HTMLUefdsButtonElement, ev: UefdsButtonCustomEvent<HTMLUefdsButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUefdsButtonElement: {
        prototype: HTMLUefdsButtonElement;
        new (): HTMLUefdsButtonElement;
    };
    interface HTMLUefdsFieldElement extends Components.UefdsField, HTMLStencilElement {
    }
    var HTMLUefdsFieldElement: {
        prototype: HTMLUefdsFieldElement;
        new (): HTMLUefdsFieldElement;
    };
    interface HTMLUefdsFieldsetElement extends Components.UefdsFieldset, HTMLStencilElement {
    }
    var HTMLUefdsFieldsetElement: {
        prototype: HTMLUefdsFieldsetElement;
        new (): HTMLUefdsFieldsetElement;
    };
    interface HTMLUefdsFormElement extends Components.UefdsForm, HTMLStencilElement {
    }
    var HTMLUefdsFormElement: {
        prototype: HTMLUefdsFormElement;
        new (): HTMLUefdsFormElement;
    };
    interface HTMLUefdsIconElement extends Components.UefdsIcon, HTMLStencilElement {
    }
    var HTMLUefdsIconElement: {
        prototype: HTMLUefdsIconElement;
        new (): HTMLUefdsIconElement;
    };
    interface HTMLUefdsInputGroupElement extends Components.UefdsInputGroup, HTMLStencilElement {
    }
    var HTMLUefdsInputGroupElement: {
        prototype: HTMLUefdsInputGroupElement;
        new (): HTMLUefdsInputGroupElement;
    };
    interface HTMLUefdsTextboxElementEventMap {
        "textboxInput": string;
        "textboxChange": string;
        "textboxFocus": void;
        "textboxBlur": void;
    }
    interface HTMLUefdsTextboxElement extends Components.UefdsTextbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUefdsTextboxElementEventMap>(type: K, listener: (this: HTMLUefdsTextboxElement, ev: UefdsTextboxCustomEvent<HTMLUefdsTextboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUefdsTextboxElementEventMap>(type: K, listener: (this: HTMLUefdsTextboxElement, ev: UefdsTextboxCustomEvent<HTMLUefdsTextboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUefdsTextboxElement: {
        prototype: HTMLUefdsTextboxElement;
        new (): HTMLUefdsTextboxElement;
    };
    interface HTMLElementTagNameMap {
        "uefds-addon": HTMLUefdsAddonElement;
        "uefds-button": HTMLUefdsButtonElement;
        "uefds-field": HTMLUefdsFieldElement;
        "uefds-fieldset": HTMLUefdsFieldsetElement;
        "uefds-form": HTMLUefdsFormElement;
        "uefds-icon": HTMLUefdsIconElement;
        "uefds-input-group": HTMLUefdsInputGroupElement;
        "uefds-textbox": HTMLUefdsTextboxElement;
    }
}
declare namespace LocalJSX {
    interface UefdsAddon {
        /**
          * @default 'start'
         */
        "align"?: 'start' | 'end';
        /**
          * @default false
         */
        "clickable"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'muted' | 'transparent';
    }
    interface UefdsButton {
        /**
          * @default false
         */
        "busy"?: boolean;
        /**
          * @default 'theme'
         */
        "color"?: 'theme' | 'success' | 'warning' | 'danger' | 'info';
        /**
          * @default 'horizontal'
         */
        "direction"?: 'vertical' | 'horizontal';
        /**
          * @default false
         */
        "disabled"?: boolean;
        "iconEnd"?: string;
        "iconStart"?: string;
        "onButtonClick"?: (event: UefdsButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        "text"?: string;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset' | 'clear';
        /**
          * @default 'solid'
         */
        "variant"?: 'outline' | 'solid' | 'subtle' | 'link';
    }
    interface UefdsField {
        "instructions"?: string;
        "label"?: string;
        /**
          * @default []
         */
        "messages"?: FieldMessage[];
        /**
          * @default false
         */
        "required"?: boolean;
        "support"?: string;
    }
    interface UefdsFieldset {
    }
    interface UefdsForm {
    }
    interface UefdsIcon {
        "name"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface UefdsInputGroup {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "error"?: boolean;
        /**
          * @default 'base'
         */
        "size"?: 'sm' | 'base' | 'lg';
    }
    interface UefdsTextbox {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "maxlength"?: number;
        "name"?: string;
        "onTextboxBlur"?: (event: UefdsTextboxCustomEvent<void>) => void;
        "onTextboxChange"?: (event: UefdsTextboxCustomEvent<string>) => void;
        "onTextboxFocus"?: (event: UefdsTextboxCustomEvent<void>) => void;
        "onTextboxInput"?: (event: UefdsTextboxCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "uefds-addon": UefdsAddon;
        "uefds-button": UefdsButton;
        "uefds-field": UefdsField;
        "uefds-fieldset": UefdsFieldset;
        "uefds-form": UefdsForm;
        "uefds-icon": UefdsIcon;
        "uefds-input-group": UefdsInputGroup;
        "uefds-textbox": UefdsTextbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uefds-addon": LocalJSX.UefdsAddon & JSXBase.HTMLAttributes<HTMLUefdsAddonElement>;
            "uefds-button": LocalJSX.UefdsButton & JSXBase.HTMLAttributes<HTMLUefdsButtonElement>;
            "uefds-field": LocalJSX.UefdsField & JSXBase.HTMLAttributes<HTMLUefdsFieldElement>;
            "uefds-fieldset": LocalJSX.UefdsFieldset & JSXBase.HTMLAttributes<HTMLUefdsFieldsetElement>;
            "uefds-form": LocalJSX.UefdsForm & JSXBase.HTMLAttributes<HTMLUefdsFormElement>;
            "uefds-icon": LocalJSX.UefdsIcon & JSXBase.HTMLAttributes<HTMLUefdsIconElement>;
            "uefds-input-group": LocalJSX.UefdsInputGroup & JSXBase.HTMLAttributes<HTMLUefdsInputGroupElement>;
            "uefds-textbox": LocalJSX.UefdsTextbox & JSXBase.HTMLAttributes<HTMLUefdsTextboxElement>;
        }
    }
}
