/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FieldMessage } from "./components/uefds-field/uefds-field";
export { FieldMessage } from "./components/uefds-field/uefds-field";
export namespace Components {
    interface BaseButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
    }
    interface BaseFieldLabel {
        /**
          * @default false
         */
        "required": boolean;
    }
    interface BaseFieldMessage {
        "icon": string;
        /**
          * @default 'danger'
         */
        "variant": 'danger' | 'warning' | 'info';
    }
    interface BaseGroupAddon {
        /**
          * @default 'start'
         */
        "align": 'start' | 'end';
        /**
          * @default false
         */
        "clickable": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'muted' | 'transparent';
    }
    interface BaseIcon {
        "name": string;
    }
    interface BaseInput {
        /**
          * @default false
         */
        "disabled": boolean;
        "maxlength": number;
        "name": string;
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface BaseInputGroup {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "error": boolean;
        /**
          * @default 'base'
         */
        "size": 'sm' | 'base' | 'lg';
    }
    interface BaseLabel {
    }
    interface BaseText {
    }
    interface UefdsButton {
        /**
          * @default false
         */
        "busy": boolean;
        /**
          * @default 'theme'
         */
        "color": 'theme' | 'success' | 'warning' | 'danger' | 'info';
        /**
          * @default 'horizontal'
         */
        "direction": 'vertical' | 'horizontal';
        /**
          * @default false
         */
        "disabled": boolean;
        "iconEnd": string;
        "iconStart": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        "text": string;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset' | 'clear';
        /**
          * @default 'solid'
         */
        "variant": 'outline' | 'solid' | 'subtle' | 'link';
    }
    interface UefdsField {
        "instructions": string;
        "label": string;
        /**
          * @default []
         */
        "messages": FieldMessage[];
        /**
          * @default false
         */
        "required": boolean;
        "support": string;
    }
    interface UefdsFieldset {
    }
    interface UefdsForm {
    }
    interface UefdsIcon {
        "name": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg' | 'xl';
    }
    interface UefdsInputGroup {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "error": boolean;
        /**
          * @default 'base'
         */
        "size": 'sm' | 'base' | 'lg';
    }
    interface UefdsTextbox {
        /**
          * @default false
         */
        "disabled": boolean;
        "maxlength": number;
        "name": string;
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface BaseButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBaseButtonElement;
}
export interface BaseInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBaseInputElement;
}
export interface UefdsTextboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUefdsTextboxElement;
}
declare global {
    interface HTMLBaseButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLBaseButtonElement extends Components.BaseButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBaseButtonElementEventMap>(type: K, listener: (this: HTMLBaseButtonElement, ev: BaseButtonCustomEvent<HTMLBaseButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBaseButtonElementEventMap>(type: K, listener: (this: HTMLBaseButtonElement, ev: BaseButtonCustomEvent<HTMLBaseButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBaseButtonElement: {
        prototype: HTMLBaseButtonElement;
        new (): HTMLBaseButtonElement;
    };
    interface HTMLBaseFieldLabelElement extends Components.BaseFieldLabel, HTMLStencilElement {
    }
    var HTMLBaseFieldLabelElement: {
        prototype: HTMLBaseFieldLabelElement;
        new (): HTMLBaseFieldLabelElement;
    };
    interface HTMLBaseFieldMessageElement extends Components.BaseFieldMessage, HTMLStencilElement {
    }
    var HTMLBaseFieldMessageElement: {
        prototype: HTMLBaseFieldMessageElement;
        new (): HTMLBaseFieldMessageElement;
    };
    interface HTMLBaseGroupAddonElement extends Components.BaseGroupAddon, HTMLStencilElement {
    }
    var HTMLBaseGroupAddonElement: {
        prototype: HTMLBaseGroupAddonElement;
        new (): HTMLBaseGroupAddonElement;
    };
    interface HTMLBaseIconElement extends Components.BaseIcon, HTMLStencilElement {
    }
    var HTMLBaseIconElement: {
        prototype: HTMLBaseIconElement;
        new (): HTMLBaseIconElement;
    };
    interface HTMLBaseInputElementEventMap {
        "inputInput": string;
        "inputChange": string;
        "inputFocus": void;
        "inputBlur": void;
    }
    interface HTMLBaseInputElement extends Components.BaseInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBaseInputElementEventMap>(type: K, listener: (this: HTMLBaseInputElement, ev: BaseInputCustomEvent<HTMLBaseInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBaseInputElementEventMap>(type: K, listener: (this: HTMLBaseInputElement, ev: BaseInputCustomEvent<HTMLBaseInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBaseInputElement: {
        prototype: HTMLBaseInputElement;
        new (): HTMLBaseInputElement;
    };
    interface HTMLBaseInputGroupElement extends Components.BaseInputGroup, HTMLStencilElement {
    }
    var HTMLBaseInputGroupElement: {
        prototype: HTMLBaseInputGroupElement;
        new (): HTMLBaseInputGroupElement;
    };
    interface HTMLBaseLabelElement extends Components.BaseLabel, HTMLStencilElement {
    }
    var HTMLBaseLabelElement: {
        prototype: HTMLBaseLabelElement;
        new (): HTMLBaseLabelElement;
    };
    interface HTMLBaseTextElement extends Components.BaseText, HTMLStencilElement {
    }
    var HTMLBaseTextElement: {
        prototype: HTMLBaseTextElement;
        new (): HTMLBaseTextElement;
    };
    interface HTMLUefdsButtonElement extends Components.UefdsButton, HTMLStencilElement {
    }
    var HTMLUefdsButtonElement: {
        prototype: HTMLUefdsButtonElement;
        new (): HTMLUefdsButtonElement;
    };
    interface HTMLUefdsFieldElement extends Components.UefdsField, HTMLStencilElement {
    }
    var HTMLUefdsFieldElement: {
        prototype: HTMLUefdsFieldElement;
        new (): HTMLUefdsFieldElement;
    };
    interface HTMLUefdsFieldsetElement extends Components.UefdsFieldset, HTMLStencilElement {
    }
    var HTMLUefdsFieldsetElement: {
        prototype: HTMLUefdsFieldsetElement;
        new (): HTMLUefdsFieldsetElement;
    };
    interface HTMLUefdsFormElement extends Components.UefdsForm, HTMLStencilElement {
    }
    var HTMLUefdsFormElement: {
        prototype: HTMLUefdsFormElement;
        new (): HTMLUefdsFormElement;
    };
    interface HTMLUefdsIconElement extends Components.UefdsIcon, HTMLStencilElement {
    }
    var HTMLUefdsIconElement: {
        prototype: HTMLUefdsIconElement;
        new (): HTMLUefdsIconElement;
    };
    interface HTMLUefdsInputGroupElement extends Components.UefdsInputGroup, HTMLStencilElement {
    }
    var HTMLUefdsInputGroupElement: {
        prototype: HTMLUefdsInputGroupElement;
        new (): HTMLUefdsInputGroupElement;
    };
    interface HTMLUefdsTextboxElementEventMap {
        "textboxInput": string;
        "textboxChange": string;
        "textboxFocus": void;
        "textboxBlur": void;
    }
    interface HTMLUefdsTextboxElement extends Components.UefdsTextbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUefdsTextboxElementEventMap>(type: K, listener: (this: HTMLUefdsTextboxElement, ev: UefdsTextboxCustomEvent<HTMLUefdsTextboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUefdsTextboxElementEventMap>(type: K, listener: (this: HTMLUefdsTextboxElement, ev: UefdsTextboxCustomEvent<HTMLUefdsTextboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUefdsTextboxElement: {
        prototype: HTMLUefdsTextboxElement;
        new (): HTMLUefdsTextboxElement;
    };
    interface HTMLElementTagNameMap {
        "base-button": HTMLBaseButtonElement;
        "base-field-label": HTMLBaseFieldLabelElement;
        "base-field-message": HTMLBaseFieldMessageElement;
        "base-group-addon": HTMLBaseGroupAddonElement;
        "base-icon": HTMLBaseIconElement;
        "base-input": HTMLBaseInputElement;
        "base-input-group": HTMLBaseInputGroupElement;
        "base-label": HTMLBaseLabelElement;
        "base-text": HTMLBaseTextElement;
        "uefds-button": HTMLUefdsButtonElement;
        "uefds-field": HTMLUefdsFieldElement;
        "uefds-fieldset": HTMLUefdsFieldsetElement;
        "uefds-form": HTMLUefdsFormElement;
        "uefds-icon": HTMLUefdsIconElement;
        "uefds-input-group": HTMLUefdsInputGroupElement;
        "uefds-textbox": HTMLUefdsTextboxElement;
    }
}
declare namespace LocalJSX {
    interface BaseButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onButtonClick"?: (event: BaseButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface BaseFieldLabel {
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface BaseFieldMessage {
        "icon"?: string;
        /**
          * @default 'danger'
         */
        "variant"?: 'danger' | 'warning' | 'info';
    }
    interface BaseGroupAddon {
        /**
          * @default 'start'
         */
        "align"?: 'start' | 'end';
        /**
          * @default false
         */
        "clickable"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'muted' | 'transparent';
    }
    interface BaseIcon {
        "name"?: string;
    }
    interface BaseInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "maxlength"?: number;
        "name"?: string;
        "onInputBlur"?: (event: BaseInputCustomEvent<void>) => void;
        "onInputChange"?: (event: BaseInputCustomEvent<string>) => void;
        "onInputFocus"?: (event: BaseInputCustomEvent<void>) => void;
        "onInputInput"?: (event: BaseInputCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface BaseInputGroup {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "error"?: boolean;
        /**
          * @default 'base'
         */
        "size"?: 'sm' | 'base' | 'lg';
    }
    interface BaseLabel {
    }
    interface BaseText {
    }
    interface UefdsButton {
        /**
          * @default false
         */
        "busy"?: boolean;
        /**
          * @default 'theme'
         */
        "color"?: 'theme' | 'success' | 'warning' | 'danger' | 'info';
        /**
          * @default 'horizontal'
         */
        "direction"?: 'vertical' | 'horizontal';
        /**
          * @default false
         */
        "disabled"?: boolean;
        "iconEnd"?: string;
        "iconStart"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        "text"?: string;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset' | 'clear';
        /**
          * @default 'solid'
         */
        "variant"?: 'outline' | 'solid' | 'subtle' | 'link';
    }
    interface UefdsField {
        "instructions"?: string;
        "label"?: string;
        /**
          * @default []
         */
        "messages"?: FieldMessage[];
        /**
          * @default false
         */
        "required"?: boolean;
        "support"?: string;
    }
    interface UefdsFieldset {
    }
    interface UefdsForm {
    }
    interface UefdsIcon {
        "name"?: string;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface UefdsInputGroup {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "error"?: boolean;
        /**
          * @default 'base'
         */
        "size"?: 'sm' | 'base' | 'lg';
    }
    interface UefdsTextbox {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "maxlength"?: number;
        "name"?: string;
        "onTextboxBlur"?: (event: UefdsTextboxCustomEvent<void>) => void;
        "onTextboxChange"?: (event: UefdsTextboxCustomEvent<string>) => void;
        "onTextboxFocus"?: (event: UefdsTextboxCustomEvent<void>) => void;
        "onTextboxInput"?: (event: UefdsTextboxCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "base-button": BaseButton;
        "base-field-label": BaseFieldLabel;
        "base-field-message": BaseFieldMessage;
        "base-group-addon": BaseGroupAddon;
        "base-icon": BaseIcon;
        "base-input": BaseInput;
        "base-input-group": BaseInputGroup;
        "base-label": BaseLabel;
        "base-text": BaseText;
        "uefds-button": UefdsButton;
        "uefds-field": UefdsField;
        "uefds-fieldset": UefdsFieldset;
        "uefds-form": UefdsForm;
        "uefds-icon": UefdsIcon;
        "uefds-input-group": UefdsInputGroup;
        "uefds-textbox": UefdsTextbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "base-button": LocalJSX.BaseButton & JSXBase.HTMLAttributes<HTMLBaseButtonElement>;
            "base-field-label": LocalJSX.BaseFieldLabel & JSXBase.HTMLAttributes<HTMLBaseFieldLabelElement>;
            "base-field-message": LocalJSX.BaseFieldMessage & JSXBase.HTMLAttributes<HTMLBaseFieldMessageElement>;
            "base-group-addon": LocalJSX.BaseGroupAddon & JSXBase.HTMLAttributes<HTMLBaseGroupAddonElement>;
            "base-icon": LocalJSX.BaseIcon & JSXBase.HTMLAttributes<HTMLBaseIconElement>;
            "base-input": LocalJSX.BaseInput & JSXBase.HTMLAttributes<HTMLBaseInputElement>;
            "base-input-group": LocalJSX.BaseInputGroup & JSXBase.HTMLAttributes<HTMLBaseInputGroupElement>;
            "base-label": LocalJSX.BaseLabel & JSXBase.HTMLAttributes<HTMLBaseLabelElement>;
            "base-text": LocalJSX.BaseText & JSXBase.HTMLAttributes<HTMLBaseTextElement>;
            "uefds-button": LocalJSX.UefdsButton & JSXBase.HTMLAttributes<HTMLUefdsButtonElement>;
            "uefds-field": LocalJSX.UefdsField & JSXBase.HTMLAttributes<HTMLUefdsFieldElement>;
            "uefds-fieldset": LocalJSX.UefdsFieldset & JSXBase.HTMLAttributes<HTMLUefdsFieldsetElement>;
            "uefds-form": LocalJSX.UefdsForm & JSXBase.HTMLAttributes<HTMLUefdsFormElement>;
            "uefds-icon": LocalJSX.UefdsIcon & JSXBase.HTMLAttributes<HTMLUefdsIconElement>;
            "uefds-input-group": LocalJSX.UefdsInputGroup & JSXBase.HTMLAttributes<HTMLUefdsInputGroupElement>;
            "uefds-textbox": LocalJSX.UefdsTextbox & JSXBase.HTMLAttributes<HTMLUefdsTextboxElement>;
        }
    }
}
